### ISSUE TITLE
missing refactor

### ISSUE THREAD

**Issue by jbrucker** [boom210232/refactoring-practice#1]
https://github.com/boom210232/refactoring-practice/blob/70bf90aa37ac74edcc2ba556720e8813d1c967c8/recipe/main.py#L17

you didn't refactor this one.

**Comment by boom210232** [comment]
@jbrucker Sorry for that. I didn't forget but I keep it to show how it differs when I turn back to read.
But Can I add a new refactor line below to show that I refactor this but keep these lines as a reference?

**Comment by boom210232** [comment]
@jbrucker  I already fix it commit 6eaf878. (latest commit)
Can you recheck again, please?
Thank you for your issue announce.

**Comment by jbrucker** [comment]
> I didn't forget but I keep it to show how it differs when I turn back to read.
> But Can I add a new refactor line below to show that I refactor this but keep these lines as a reference?

You can keep the original code if you want.
Or, view a "diff" between the first commit and your final commit to see all the
differences. Github has a visual side-by-side diff tool. So do PyCharm, VS Code, and gitk.

You can install a stand-alone GUI "diff" viewer that can also be used to visually merge
and fix conflicts. Type "git difftool --tool-help" for a list.  See the Git online docs for how to 
configure and use.  I use `meld` (`diffuse` is good, too).
